spring.application.name=track
server.port:9099
spring.main.allow-circular-reference=true
spring.redis.host=localhost
spring.redis.port=6379
spring.session.store-type=redis
spring.session.timeout=1000
 