server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/products/**
            
        - id: order-service
          uri: http://localhost:8086
          predicates:
            - Path=/orders/**