spring.application.name=Bike-rental
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=root@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.web-application-type=none